site_name: Guardiões da saúde
pages:
  - Home: 'index.md'
  - Planejamento: 'planejamento/planejamento.md'
  - Pré-Rastreabilidade:
    - Rich Pictures: 'pre-rastreabilidade/RichPictures.md'
  - Elicitação:
    - Questionário: 'elicitacao/elicitacao_tecnicas/questionario.md'
    - Introspecção: 'elicitacao/elicitacao_tecnicas/Introspeccao.md'
    - Storytelling: 'elicitacao/elicitacao_tecnicas/storytelling.md'
    - Priorização:
        - 'elicitacao/priorizacao/MoSCow.md'
        - 'elicitacao/priorizacao/FirstThingsFirst.md'
  - Modelagem:
    - Cenários: 'modelagem/cenarios.md'
    - Léxicos: 'modelagem/lexicos.md'
    - Diagramas de Casos de Uso: 'modelagem/dcu.md'
    - Especificação Suplementar: 'modelagem/es.md'
    - NFR Framework: 'modelagem/NFR.md'
    - Backlog: 'modelagem/backlog.md'
  - Análise:
    - Validação: 'verificacao-e-validacao/validacao/validacaoinf.md'
    - Verificação:
        - Léxicos: 'verificacao-e-validacao/verificacao/lexico.md'
        - Backlog: 'verificacao-e-validacao/verificacao/backlog.md'
        - Cenários: 'verificacao-e-validacao/verificacao/cenarios.md'
        - NFR: 'verificacao-e-validacao/verificacao/NFR.md'
        - Casos de Uso: 'verificacao-e-validacao/verificacao/CasosdeUso.md'
        - Especificação suplementar: 'verificacao-e-validacao/verificacao/ESP.md'
        - Introspecção: 'verificacao-e-validacao/verificacao/introspeccao.md'
        - Questionário: 'verificacao-e-validacao/verificacao/questionario.md'
        - Storytelling: 'verificacao-e-validacao/verificacao/story.md'
  - Pós-rastreabilidade:
    - Forward-from: 'pos-rastreabilidade/forward.md'
    - Backward-from: 'pos-rastreabilidade/backward.md'
  - Aplicação: 'App.md'
  - Apresentações: 'apresentacoes/apresentacoes.md'
extra_css: 
  - assets/css/extra.css
theme:
  name: material
  logo: assets/logo.png
  language: pt
